=== 4LlW3R/mvs/analytics/geo-data-schemas/schemas/objects/roadConditionStatus.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "RoadConditionStatus",
  "id": "roadConditionStatus.json",
  "type": "object",
  "required": ["Domain", "Id", "EntityType", "SchemaVersion", "data"],
  "properties": {
    "Domain": {
      "type": "string"
    },
    "Id": {
      "type": "string"
    },
    "EntityType": {
      "type": "string"
    },
    "SchemaVersion": {
      "type": "number"
    },
    "data": {
      "allOf": [
        {
          "$ref": "geojson.json"
        },
        {
          "$ref": "definitions.json#/definitions/roadConditionStatus"
        },
        {
          "$ref": "definitions.json#/definitions/geojsonProperties"
        }
      ]
    }
  }
}

=== 4LlW3R/mvs/analytics/java/road-condition-violation-detection/src/test/resources/example_road_condition.json
{
  "Domain": "rcdb.tengizchevroil.com",
  "EntityType": "RCDB",
  "Id": "9b5ea626-6e92-433c-95f7-d62d521e6164",
  "SchemaVersion": 1,
  "data": {
    "type": "Feature",
    "crs": {
      "type": "name",
      "properties": {
        "name": "epsg:4326"
      }
    },
    "geometry": {
      "type": "GeometryCollection",
      "geometries": [
        {
          "type": "Polygon",
          "coordinates": [
            [
              [
                53.379822,
                46.822617
              ],
              [
                53.291931,
                46.562637
              ],
              [
                53.319397,
                46.365884
              ],
              [
                53.725891,
                46.271037
              ],
              [
                54.363098,
                46.24825
              ],
              [
                54.582825,
                46.777493
              ],
              [
                54.456482,
                47.070122
              ],
              [
                53.802795,
                46.998988
              ],
              [
                53.379822,
                46.822617
              ]
            ]
          ]
        },
        {
          "type": "Polygon",
          "coordinates": [
            [
              [
                51.81427,
                47.196095
              ],
              [
                51.720886,
                47.040968
              ],
              [
                51.733246,
                46.995091
              ],
              [
                51.877441,
                46.98385
              ],
              [
                51.994171,
                47.009139
              ],
              [
                52.057343,
                47.104569
              ],
              [
                52.120514,
                47.225015
              ],
              [
                51.954346,
                47.2418
              ],
              [
                51.81427,
                47.196095
              ]
            ]
          ]
        },
        {
          "type": "Polygon",
          "coordinates": [
            [
              [
                50.06813,
                46.798574
              ],
              [
                50.059204,
                46.732726
              ],
              [
                50.095596,
                46.673395
              ],
              [
                50.19516,
                46.714839
              ],
              [
                50.282364,
                46.763779
              ],
              [
                50.254211,
                46.795284
              ],
              [
                50.06813,
                46.798574
              ]
            ]
          ]
        },
        {
          "type": "LineString",
          "coordinates": [
            [
              49.592285,
              46.700017
            ],
            [
              49.768066,
              46.722616
            ],
            [
              49.985046,
              46.730147
            ],
            [
              50.127869,
              46.750852
            ],
            [
              50.267944,
              46.83547
            ],
            [
              50.366821,
              46.908698
            ],
            [
              50.397034,
              46.958699
            ],
            [
              50.458832,
              46.985874
            ],
            [
              50.581055,
              46.994304
            ],
            [
              50.667572,
              47.025206
            ]
          ]
        }
      ]
    },
    "properties": {
      "uuid": "1",
      "domain": "rcdb.tengizchevroil.com",
      "version": 1,
      "RoadConditionId": 1,
      "RoadConditionType": "Amber",
      "RoadConditionEventType": "Approved",
      "StartDateTime": "2018-06-21T12:46:00Z",
      "EffectiveDateTime": "2000-01-01T22:45:07Z",
      "EndDateTime": "2000-01-02T14:48:32Z",
      "Graphic": {
        "attributes": {
          "center": {
            "lat": 47.0888252,
            "lng": 52.6547241
          },
          "zoom": 7
        }
      }
    }
  }
}
